[project]
name = "datasources"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "aiokafka>=0.12.0",
    "confluent-kafka>=2.10.0",
    "faker>=37.1.0",
]
